name: github actions demo

on: 
  push:
ã€€  breanches:
     - main
    paths-ignore:
     - .github/**
  pull_request:
     branches:
       - main
  schedule:
    - corn: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build
    runs-on: ubunts-latest
    steps:
      - run:
        echo "event name: $(( github.event_name ))"
        echo "branch: &(( github.ref ))"

     - uses: actions/chekout@v4.1

     - run: tree
